apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "janus.fullname" . }}
  labels:
{{ include "janus.labels" . | indent 4 }}
{{ toYaml .Values.deployment.labels | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "janus.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ toYaml .Values.deployment.labels | indent 8 }}
        app.kubernetes.io/name: {{ include "janus.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if or (.Values.deployment.podAnnotations) (.Values.deployment.PodAnnotations) }}
      annotations:
{{- with .Values.deployment.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
    spec:
    {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              name: http-private
              protocol: TCP
          env:
            {{- if .Values.deployment.valuesFrom }}
            {{ toYaml .Values.deployment.valuesFrom  | nindent 12 }}
            {{- end}}
            {{- if .Values.envConfig }}
            {{- range $key, $value := .Values.envConfig }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.deployment.databaseDSN }}
            - name: "DATABASE_DSN"
              value: "{{ . }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
