version: '3.3'
services:

  janus:
    image: harbor.whalebone.io/whalebone/janus:3.8.22-wb-0.0.4
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      HTTP_PORT: 9090
      LOG_LEVEL: debug 
      ADMIN_HTTP_PORT: 9091 
      ADMIN_JWT_SECRET: secret 
      ADMIN_BASIC_PASS: admin
      WB_API_0: public-api
      WB_API_0_LISTEN_PATH: /public-api/*
      WB_API_0_UPSTREAM_TARGET: http://docker.for.mac.localhost:8080/whalebone/1
      WB_API_0_RATE_LIMIT_VALUE: 5-M
      WB_API_0_WB_AUTH_LOGIN_ENDPOINT: http://docker.for.mac.localhost:7070/public-api/credentials/login
      WB_API_0_WB_AUTH_CACHE_TTL_SECS: 30
      WB_API_0_WB_AUTH_CACHE_CLEANUP_SECS: 60
      WB_API_1: test
      WB_API_1_LISTEN_PATH: /test-api/*
      WB_API_1_UPSTREAM_TARGET: http://test-api
      WB_API_1_RATE_LIMIT_VALUE: 10-S
      WB_API_1_WB_AUTH_ENABLED: "false"
      WB_API_2: disabled
      WB_API_2_ENABLED: "true"
      WB_API_2_LISTEN_PATH: /disabled-api/*
      WB_API_2_UPSTREAM_TARGET: http://disabled-api
      WB_API_2_RATE_LIMIT_ENABLED: "true"
      WB_API_2_RATE_LIMIT_VALUE: 10-S
      WB_API_2_WB_AUTH_ENABLED: "true"
      
