#!/bin/sh

# prepare janus configuration
sed -i "s|@HTTP_PORT@|${HTTP_PORT:-8080}|g" ${JANUS_CONF}
sed -i "s|@LOG_LEVEL@|${LOG_LEVEL:-info}|g" ${JANUS_CONF}
sed -i "s|@ADMIN_HTTP_PORT@|${ADMIN_HTTP_PORT:-8081}|g" ${JANUS_CONF}
sed -i "s|@ADMIN_JWT_SECRET@|${ADMIN_JWT_SECRET}|g" ${JANUS_CONF}
sed -i "s|@ADMIN_BASIC_PASS@|${ADMIN_BASIC_PASS}|g" ${JANUS_CONF}

# prepare public-api endpoint config
sed -i "s|@PUBLIC_API_ENABLED@|${PUBLIC_API_ENABLED:-true}|g" ${PUBLIC_API_CONF}
sed -i "s|@PUBLIC_API_PRESERVE_HOST@|${PUBLIC_API_PRESERVE_HOST:-false}|g" ${PUBLIC_API_CONF}
sed -i "s|@PUBLIC_API_LISTEN_PATH@|${PUBLIC_API_LISTEN_PATH}|g" ${PUBLIC_API_CONF}
sed -i "s|@PUBLIC_API_UPSTREAM_TARGET@|${PUBLIC_API_UPSTREAM_TARGET}|g" ${PUBLIC_API_CONF}
sed -i "s|@PUBLIC_API_STRIP_PATH@|${PUBLIC_API_STRIP_PATH:-true}|g" ${PUBLIC_API_CONF}
sed -i "s|@PUBLIC_API_APPEND_PATH@|${PUBLIC_API_APPEND_PATH:-true}|g" ${PUBLIC_API_CONF}

sed -i "s|@PUBLIC_API_RATE_LIMIT_ENABLED@|${PUBLIC_API_RATE_LIMIT_ENABLED:-true}|g" ${PUBLIC_API_CONF}
sed -i "s|@PUBLIC_API_RATE_LIMIT_VALUE@|${PUBLIC_API_RATE_LIMIT_VALUE:-5-M}|g" ${PUBLIC_API_CONF}

sed -i "s|@PUBLIC_API_WB_AUTH_ENABLED@|${PUBLIC_API_WB_AUTH_ENABLED:-true}|g" ${PUBLIC_API_CONF}
sed -i "s|@PUBLIC_API_WB_AUTH_LOGIN_ENDPOINT@|${PUBLIC_API_WB_AUTH_LOGIN_ENDPOINT}|g" ${PUBLIC_API_CONF}
sed -i "s|@PUBLIC_API_WB_AUTH_CACHE_TTL_SECS@|${PUBLIC_API_WB_AUTH_CACHE_TTL_SECS:-30}|g" ${PUBLIC_API_CONF}
sed -i "s|@PUBLIC_API_WB_AUTH_CACHE_CLEANUP_SECS@|${PUBLIC_API_WB_AUTH_CACHE_CLEANUP_SECS:-60}|g" ${PUBLIC_API_CONF}

# start the service
/janus -c /etc/janus/janus.toml start
